-- H2 Database Schema for Demo Environment
-- H2 2.4+ 対応（MODE=PostgreSQL）

-- ============================================
-- 勘定科目テーブル (V1, V6)
-- ============================================
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    account_type VARCHAR(20) NOT NULL,
    kana VARCHAR(40),
    bspl_category CHAR(1),
    transaction_element_category CHAR(1),
    expense_category CHAR(1),
    is_summary_account BOOLEAN DEFAULT false NOT NULL,
    display_order INTEGER,
    is_aggregation_target BOOLEAN DEFAULT true NOT NULL,
    balance DECIMAL(15,2) DEFAULT 0 NOT NULL,
    tax_transaction_code VARCHAR(2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_accounts_code ON accounts(code);
CREATE INDEX IF NOT EXISTS idx_accounts_account_type ON accounts(account_type);
CREATE INDEX IF NOT EXISTS idx_accounts_bspl_category ON accounts(bspl_category);
CREATE INDEX IF NOT EXISTS idx_accounts_display_order ON accounts(display_order);

-- ============================================
-- ユーザーテーブル (V2, V4)
-- ============================================
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    locked BOOLEAN NOT NULL DEFAULT false,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_active ON users(active);

-- ============================================
-- 仕訳テーブル (V5, V8, V11)
-- ============================================
CREATE TABLE IF NOT EXISTS journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_date DATE NOT NULL,
    description VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by VARCHAR(36),
    approved_by VARCHAR(36),
    approved_at TIMESTAMP,
    rejected_by VARCHAR(36),
    rejected_at TIMESTAMP,
    rejection_reason VARCHAR(500),
    confirmed_by VARCHAR(36),
    confirmed_at TIMESTAMP,
    voucher_number VARCHAR(20),
    input_date DATE,
    is_closing_entry INTEGER DEFAULT 0 NOT NULL,
    is_single_entry INTEGER DEFAULT 0 NOT NULL,
    voucher_type INTEGER DEFAULT 0 NOT NULL,
    is_recurring INTEGER DEFAULT 0 NOT NULL,
    employee_code VARCHAR(10),
    department_code VARCHAR(5),
    is_red_slip INTEGER DEFAULT 0 NOT NULL,
    red_black_voucher_number VARCHAR(20),
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_journal_entries_user FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_journal_entries_approver FOREIGN KEY (approved_by) REFERENCES users(id)
    ,CONSTRAINT fk_journal_entries_rejected_by FOREIGN KEY (rejected_by) REFERENCES users(id)
    ,CONSTRAINT fk_journal_entries_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES users(id)
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_journal_entries_date ON journal_entries(journal_date);
CREATE INDEX IF NOT EXISTS idx_journal_entries_status ON journal_entries(status);
CREATE INDEX IF NOT EXISTS idx_journal_entries_approved_by ON journal_entries(approved_by);
CREATE INDEX IF NOT EXISTS idx_journal_entries_rejected_by ON journal_entries(rejected_by);
CREATE INDEX IF NOT EXISTS idx_journal_entries_confirmed_by ON journal_entries(confirmed_by);
CREATE INDEX IF NOT EXISTS idx_journal_entries_is_closing ON journal_entries(is_closing_entry);
CREATE INDEX IF NOT EXISTS idx_journal_entries_is_red_slip ON journal_entries(is_red_slip);
CREATE INDEX IF NOT EXISTS idx_journal_entries_department ON journal_entries(department_code);
CREATE UNIQUE INDEX IF NOT EXISTS idx_journal_entries_voucher_number ON journal_entries(voucher_number);

-- ============================================
-- 仕訳明細テーブル (V5, V8)
-- ============================================
CREATE TABLE IF NOT EXISTS journal_entry_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    debit_amount DECIMAL(15, 2) DEFAULT 0,
    credit_amount DECIMAL(15, 2) DEFAULT 0,
    line_description VARCHAR(1000),
    CONSTRAINT fk_journal_entry_lines_entry FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id) ON DELETE CASCADE,
    CONSTRAINT fk_journal_entry_lines_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT journal_entry_lines_unique_entry_line UNIQUE (journal_entry_id, line_number)
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_journal_entry_lines_journal_entry ON journal_entry_lines(journal_entry_id);

-- ============================================
-- 仕訳貸借明細テーブル (V8)
-- ============================================
CREATE TABLE IF NOT EXISTS journal_entry_debit_credit (
    journal_entry_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    debit_credit_type CHAR(1) NOT NULL,
    currency_code VARCHAR(3) DEFAULT 'JPY' NOT NULL,
    exchange_rate NUMERIC(10,4) DEFAULT 1.0000 NOT NULL,
    department_code VARCHAR(5),
    project_code VARCHAR(10),
    account_code VARCHAR(10) NOT NULL,
    sub_account_code VARCHAR(10),
    amount NUMERIC(15,2) NOT NULL,
    base_currency_amount NUMERIC(15,2) NOT NULL,
    tax_category VARCHAR(2),
    tax_rate INTEGER,
    tax_calculation_category VARCHAR(2),
    due_date DATE,
    is_cash_flow INTEGER DEFAULT 0 NOT NULL,
    segment_code VARCHAR(10),
    counter_account_code VARCHAR(10),
    counter_sub_account_code VARCHAR(10),
    tag_code VARCHAR(1),
    tag_content VARCHAR(60),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (journal_entry_id, line_number, debit_credit_type),
    CONSTRAINT fk_journal_entry_dc_line FOREIGN KEY (journal_entry_id, line_number) REFERENCES journal_entry_lines (journal_entry_id, line_number) ON DELETE CASCADE,
    CONSTRAINT fk_journal_entry_dc_account FOREIGN KEY (account_code) REFERENCES accounts (code)
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_journal_entry_debit_credit_entry ON journal_entry_debit_credit(journal_entry_id);
CREATE INDEX IF NOT EXISTS idx_journal_entry_debit_credit_account ON journal_entry_debit_credit(account_code);
CREATE INDEX IF NOT EXISTS idx_journal_entry_debit_credit_department ON journal_entry_debit_credit(department_code);
CREATE INDEX IF NOT EXISTS idx_journal_entry_debit_credit_project ON journal_entry_debit_credit(project_code);

-- ============================================
-- 課税取引マスタ (V7)
-- ============================================
CREATE TABLE IF NOT EXISTS tax_transactions (
    tax_code VARCHAR(2) PRIMARY KEY,
    tax_name VARCHAR(20) NOT NULL,
    tax_rate DECIMAL(5, 3) NOT NULL DEFAULT 0.000,
    description VARCHAR(200),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ============================================
-- 勘定科目構成マスタ (V7)
-- ============================================
CREATE TABLE IF NOT EXISTS account_structures (
    account_code VARCHAR(20) PRIMARY KEY,
    account_path VARCHAR(200) NOT NULL,
    hierarchy_level INTEGER NOT NULL DEFAULT 1,
    parent_account_code VARCHAR(20),
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_account_structure_account FOREIGN KEY (account_code) REFERENCES accounts(code) ON DELETE CASCADE
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_account_structures_path ON account_structures (account_path);
CREATE INDEX IF NOT EXISTS idx_account_structures_parent ON account_structures (parent_account_code);

-- ============================================
-- 日次勘定科目残高テーブル (V9)
-- ============================================
CREATE TABLE IF NOT EXISTS daily_account_balances (
    posting_date DATE NOT NULL,
    account_code VARCHAR(10) NOT NULL,
    sub_account_code VARCHAR(10) NOT NULL DEFAULT '',
    department_code VARCHAR(5) NOT NULL DEFAULT '',
    project_code VARCHAR(10) NOT NULL DEFAULT '',
    is_closing_entry INTEGER NOT NULL DEFAULT 0,
    debit_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (posting_date, account_code, sub_account_code, department_code, project_code, is_closing_entry),
    CONSTRAINT fk_daily_balance_account FOREIGN KEY (account_code) REFERENCES accounts (code)
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_daily_account_balances_date ON daily_account_balances(posting_date);
CREATE INDEX IF NOT EXISTS idx_daily_account_balances_account ON daily_account_balances(account_code);
CREATE INDEX IF NOT EXISTS idx_daily_account_balances_department ON daily_account_balances(department_code);
CREATE INDEX IF NOT EXISTS idx_daily_account_balances_project ON daily_account_balances(project_code);

-- ============================================
-- 月次勘定科目残高テーブル (V9)
-- ============================================
CREATE TABLE IF NOT EXISTS monthly_account_balances (
    fiscal_period INTEGER NOT NULL,
    "month" INTEGER NOT NULL,
    account_code VARCHAR(10) NOT NULL,
    sub_account_code VARCHAR(10) NOT NULL DEFAULT '',
    department_code VARCHAR(5) NOT NULL DEFAULT '',
    project_code VARCHAR(10) NOT NULL DEFAULT '',
    is_closing_entry INTEGER NOT NULL DEFAULT 0,
    opening_balance NUMERIC(15,2) NOT NULL DEFAULT 0,
    debit_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    closing_balance NUMERIC(15,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (fiscal_period, "month", account_code, sub_account_code, department_code, project_code, is_closing_entry),
    CONSTRAINT fk_monthly_balance_account FOREIGN KEY (account_code) REFERENCES accounts (code)
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_monthly_account_balances_period_month ON monthly_account_balances(fiscal_period, "month");
CREATE INDEX IF NOT EXISTS idx_monthly_account_balances_account ON monthly_account_balances(account_code);

-- ============================================
-- 自動仕訳管理テーブル (V9)
-- ============================================
CREATE TABLE IF NOT EXISTS auto_journal_management (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table_name VARCHAR(100) NOT NULL UNIQUE,
    last_processed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ============================================
-- 自動仕訳パターンテーブル (V9)
-- ============================================
CREATE TABLE IF NOT EXISTS auto_journal_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_code VARCHAR(20) NOT NULL UNIQUE,
    pattern_name VARCHAR(100) NOT NULL,
    source_table_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_auto_journal_patterns_source ON auto_journal_patterns(source_table_name);

-- ============================================
-- 自動仕訳パターン明細テーブル (V9)
-- ============================================
CREATE TABLE IF NOT EXISTS auto_journal_pattern_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    debit_credit_type CHAR(1) NOT NULL,
    account_code VARCHAR(10) NOT NULL,
    amount_formula VARCHAR(200) NOT NULL,
    description_template VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_pattern_items_pattern FOREIGN KEY (pattern_id) REFERENCES auto_journal_patterns (id) ON DELETE CASCADE,
    CONSTRAINT fk_pattern_items_account FOREIGN KEY (account_code) REFERENCES accounts (code)
);

-- ============================================
-- 自動仕訳実行ログテーブル (V9)
-- ============================================
CREATE TABLE IF NOT EXISTS auto_journal_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_id BIGINT NOT NULL,
    executed_at TIMESTAMP NOT NULL,
    processed_count INTEGER NOT NULL DEFAULT 0,
    generated_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    message VARCHAR(500),
    error_detail CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_auto_journal_logs_pattern FOREIGN KEY (pattern_id) REFERENCES auto_journal_patterns (id)
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_auto_journal_logs_pattern ON auto_journal_logs(pattern_id);
CREATE INDEX IF NOT EXISTS idx_auto_journal_logs_executed_at ON auto_journal_logs(executed_at);

-- ============================================
-- 初期データ: 課税取引マスタ (V7)
-- ============================================
INSERT INTO tax_transactions (tax_code, tax_name, tax_rate, description) VALUES
    ('01', '課税', 0.10, '消費税が課税される取引'),
    ('02', '非課税', 0.000, '消費税が非課税の取引（土地の譲渡、住宅の貸付など）'),
    ('03', '免税', 0.000, '消費税が免税の取引（輸出取引など）'),
    ('04', '不課税', 0.000, '消費税の対象外の取引（給与、配当など）');

-- ============================================
-- 監査ログテーブル (V15)
-- H2 用: BIGINT GENERATED BY DEFAULT AS IDENTITY, IF NOT EXISTS 付きインデックス
-- PostgreSQL 版は V15__create_audit_logs_table.sql を参照
-- ============================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    action_type VARCHAR(20) NOT NULL,
    entity_type VARCHAR(50),
    entity_id VARCHAR(50),
    description CLOB,
    ip_address VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action_type ON audit_logs(action_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_type ON audit_logs(entity_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);
